### ISSUE TITLE
Warning: ZipArchive::close(): Write error: Out of memory in /code/src/Keboola/SlicedFilesPacker/App.php on line 31

### ISSUE THREAD

**Issue by Halama** [keboola/sliced-files-packer#1]
Zahlásí to jenom jako warning a komponent pak failne na:
![image](https://user-images.githubusercontent.com/903531/36098863-df7a51d2-1000-11e8-92ef-1716688f84fb.png)

**Comment by Halama** [comment]
soubor na kterém to dělá opakovaně má ve storage 586.57MB, a tabulka 14 sloupců a 15M řádků.

**Comment by Halama** [comment]
Tady jsem to nasimuloval https://connection.keboola.com/admin/projects/4088/jobs/355308580?q=

**Comment by Halama** [comment]
Zvednul jsem tomu pamet z 64M na 256M to nezabere, bude to chtit teda pofixovat a pridat do testu.

**Comment by Halama** [comment]
Zaroven to teda misto toho zalogovani warningu melo hodit exception a skoncit errorem, to chce taky fixnout.

**Comment by ujovlado** [comment]
Idem to kuknut

**Comment by ujovlado** [comment]
Je to zaujimave. Mam 2 subory, kazdy 600M, nieco podobne ako si si vygeneroval (2 stlpce, v jednom counter, v dalsom hodnota). Container som prepol na 8M (slovom osem mega) a vali to.

![screenshot_2018-02-14_16-05-10](https://user-images.githubusercontent.com/419849/36211196-db713ae6-11a0-11e8-959c-27a7e74d7241.png)

**Comment by ujovlado** [comment]
Skusam este tych vela malych 5M suborov

**Comment by Halama** [comment]
tvl, to je divny

**Comment by Halama** [comment]
ono to nejspis teda bude neco jako tohle asi https://github.com/keboola/connection/issues/1048

**Comment by Halama** [comment]
prvni fix by mohl mozna teda byt at to alespon hodi internal error, at o tom vime

**Comment by ujovlado** [comment]
Ten job co ti spadol, tak ten isty file mi presiel ...
https://connection.keboola.com/admin/projects/4088/jobs/355981425

Skusil som presne ten isty file (321 slices) opat spustit na tom cotaineri co ma 8M a takisto to preslo. T.j. s pamatou to nebude suvisiet.

![screenshot_2018-02-14_17-13-32](https://user-images.githubusercontent.com/419849/36214784-a7e384cc-11aa-11e8-819c-437c324d159d.png)

Zatial neviem, co mohlo tu pamat v containeri vyzrat, takze pofixujem aspon tie ostatne veci.

**Comment by ujovlado** [comment]
V ramci toho upratania to este switchnem na debian based (namiesto alpine) a uvidime, ci sa to bude opakovat.

**Comment by ujovlado** [comment]
Tie warningy su fixle, akurat som to otagoval, som zvedavy ci tu pamat ten debian-based fixne alebo nie

**Comment by Halama** [comment]
Vidím že od nasazení už se to nestalo, zavírám tedy.
