### ISSUE TITLE
file moved to glacier

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sliced-files-packer#7]
pokud je vyexportovaný soubor přesunutý do GLACIERu, tak
- v UI je stále tlačítko na stáhnutí
- pustí se job a ten skončí app chybou (`Failed to download file out.c-zendesk-8643.source_data.csv 407769166`)
- v UI chyba není nijak reflektovaná, modal se resetuje do původního stavu

https://connection.keboola.com/admin/projects/232/jobs/423694767?q=

http://take.ms/I1Yu2

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/input-mapping/issues/18 
https://github.com/keboola/connection/issues/1080

**Comment by ondrejhlavacek** [comment]
Jasně, fyi hlásí to `The specified key does not exist.`

**Comment by odinuv** [comment]
solved in https://keboola.atlassian.net/browse/KBC-161
